version: 2

jobs:
  test:
    working_directory: ~/wildlife
    docker:
      - image: circleci/node:10.15
    steps:
      - checkout
      - run:
          name: Install
          command: yarn install --frozen-lockfile
      - run:
          name: Lint
          command: yarn lint
      - run:
          name: Format
          command: yarn format
  deploy:
    working_directory: ~/wildlife
    docker:
      - image: circleci/node:10.15
    steps:
      - checkout
      - run:
          name: Install
          command: yarn install --frozen-lockfile
      - run:
          name: Build
          command: yarn build
      - run:
          name: Deploy
          command: yarn cdk deploy WildlifeStack

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: master
